import { chromium } from "@playwright/test";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await page.goto("http://localhost:3000/signin", { timeout: 60000 });
await page.getByTestId("signin-identifier").fill("mariama@example.sl");
await page.getByTestId("signin-password").fill("demo-password");
await page.getByTestId("signin-submit").click();
await page.getByTestId("business-name").waitFor({ timeout: 60000 });
await page.getByTestId("fab-add").click();
await page.getByTestId("choose-scan-locked").waitFor();
await page.waitForTimeout(400);
await page.screenshot({ path: "/tmp/scan-locked.png" });
await b.close();
console.log("OK");
