// MI YONE token pipeline — Phase 4 §34.
// primitives.json (private) + semantic.json (public mapping) → CSS custom properties.
// Components consume ONLY the generated --<semantic-name> variables.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const primitives = JSON.parse(readFileSync(join(root, "tokens/primitives.json"), "utf8"));
const semantic = JSON.parse(readFileSync(join(root, "tokens/semantic.json"), "utf8"));

function resolveRef(value) {
  const m = /^\{(.+)\}$/.exec(value);
  if (!m) return value; // literal (e.g. rgba scrim)
  const path = m[1].split(".");
  let node = primitives;
  for (const key of path) {
    node = node?.[key];
    if (node === undefined) throw new Error(`Unknown primitive reference: ${value}`);
  }
  if (typeof node !== "string") throw new Error(`Reference does not resolve to a value: ${value}`);
  return node;
}

const lines = Object.entries(semantic).map(([name, ref]) => `  --${name}: ${resolveRef(ref)};`);
const css = `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand. */\n:root {\n${lines.join("\n")}\n}\n`;

const outDir = join(root, "src/shared/design-system/tokens");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "tokens.css"), css);
console.log(`tokens.css written (${Object.keys(semantic).length} semantic tokens).`);
