"""initial schema — every table MI YONE has at deployment time.

Revision ID: 0001
Revises:
Create Date: 2026-09-03

Generated by autogenerate against an empty PostgreSQL 16 database and read
line by line against app/models.py. It creates the exact schema the models
describe, including every column the pre-Alembic startup shim used to add
(entry_method, created_at, origin, external_id, alert_prefs, mode, blocks_json,
status, sale_id, debt_id, idempotency_key) and the two partial unique indexes
that were missing on inventory_movements and debts (uq_movement_idempotency,
uq_debt_idempotency — the same guarantee transactions and sales already had).

Column defaults are Python-side (SQLAlchemy `default=`), exactly as
create_all produced them: every row is written through the ORM, so no DDL
default is needed and none is declared.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.config import settings


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_business_id'), 'audit_events', ['business_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('alert_prefs', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('blocks_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_business_id'), 'ai_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('business_members',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id')
    )
    op.create_index(op.f('ix_business_members_business_id'), 'business_members', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_members_user_id'), 'business_members', ['user_id'], unique=False)
    op.create_table('catalog_connections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_connections_business_id'), 'catalog_connections', ['business_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_business_id'), 'parties', ['business_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('selling_minor', sa.BigInteger(), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('image_key', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.String(length=12), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('cash_transaction_id', sa.String(length=40), nullable=True),
    sa.Column('receivable_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_occurred_at'), 'sales', ['occurred_at'], unique=False)
    op.create_index('uq_sale_idempotency', 'sales', ['business_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('transaction_categories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', 'kind')
    )
    op.create_index(op.f('ix_transaction_categories_business_id'), 'transaction_categories', ['business_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('debt_id', sa.String(length=40), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('entry_method', sa.String(length=8), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=True),
    sa.Column('reverses_transaction_id', sa.String(length=40), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('fixed_by', sa.String(length=120), nullable=True),
    sa.Column('fixed_was_minor', sa.BigInteger(), nullable=True),
    sa.Column('fixed_now_minor', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_tx_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reverses_transaction_id')
    )
    op.create_index(op.f('ix_transactions_business_id'), 'transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty_id'), 'transactions', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_transactions_debt_id'), 'transactions', ['debt_id'], unique=False)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_index('ix_tx_business_occurred', 'transactions', ['business_id', 'occurred_at'], unique=False)
    op.create_index('uq_tx_idempotency', 'transactions', ['business_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('catalog_imports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('connection_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['catalog_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_imports_business_id'), 'catalog_imports', ['business_id'], unique=False)
    op.create_index(op.f('ix_catalog_imports_created_at'), 'catalog_imports', ['created_at'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('settled_minor', sa.BigInteger(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_method', sa.String(length=8), nullable=False),
    sa.CheckConstraint('settled_minor <= amount_minor', name='ck_debt_no_oversettle'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_business_id'), 'debts', ['business_id'], unique=False)
    op.create_index(op.f('ix_debts_counterparty_id'), 'debts', ['counterparty_id'], unique=False)
    op.create_index('uq_debt_idempotency', 'debts', ['business_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sale_id', sa.String(length=40), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('unit_cost_minor', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_business_id'), 'inventory_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_occurred_at'), 'inventory_movements', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_sale_id'), 'inventory_movements', ['sale_id'], unique=False)
    op.create_index('uq_movement_idempotency', 'inventory_movements', ['business_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('catalog_import_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('import_id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_of_product_id', sa.String(length=40), nullable=True),
    sa.Column('product_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['catalog_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_import_items_business_id'), 'catalog_import_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_catalog_import_items_import_id'), 'catalog_import_items', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops EVERY table. Allowed only where data is disposable (dev/demo)."""
    if settings.env not in ("dev", "demo"):
        raise RuntimeError(
            f"Refusing to downgrade the initial migration with MIYONE_ENV={settings.env!r}: "
            "this drops every table. Restore from a backup instead."
        )
    op.drop_index(op.f('ix_catalog_import_items_import_id'), table_name='catalog_import_items')
    op.drop_index(op.f('ix_catalog_import_items_business_id'), table_name='catalog_import_items')
    op.drop_table('catalog_import_items')
    op.drop_index('uq_movement_idempotency', table_name='inventory_movements', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_inventory_movements_sale_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_occurred_at'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_business_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('uq_debt_idempotency', table_name='debts', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_debts_counterparty_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_business_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_catalog_imports_created_at'), table_name='catalog_imports')
    op.drop_index(op.f('ix_catalog_imports_business_id'), table_name='catalog_imports')
    op.drop_table('catalog_imports')
    op.drop_index('uq_tx_idempotency', table_name='transactions', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_tx_business_occurred', table_name='transactions')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_debt_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_business_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_categories_business_id'), table_name='transaction_categories')
    op.drop_table('transaction_categories')
    op.drop_index('uq_sale_idempotency', table_name='sales', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_sales_occurred_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_parties_business_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_catalog_connections_business_id'), table_name='catalog_connections')
    op.drop_table('catalog_connections')
    op.drop_index(op.f('ix_business_members_user_id'), table_name='business_members')
    op.drop_index(op.f('ix_business_members_business_id'), table_name='business_members')
    op.drop_table('business_members')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_ai_messages_created_at'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_business_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_events_business_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
